include(Accounts/Accounts.pri)
include(Chat/Chat.pri)
include(Entities/Entities.pri)
include(Handlers/Handlers.pri)
include(Maps/Maps.pri)
include(Scripting/Scripting.pri)
include(Server/Server.pri)
include(World/World.pri)
